FROM centos:7
MAINTAINER tjinjin

# setup
RUN yum update -y
RUN yum install -y rpm-build tar make

# ruby depends
RUN yum -y install readline-devel ncurses-devel gdbm-devel glibc-devel gcc openssl-devel libyaml-devel libffi-devel zlib-devel

# build
RUN mkdir -p /var/tmp/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
WORKDIR /var/tmp/rpmbuild
ADD rubybuild.sh /var/tmp/rpmbuild/rubybuild.sh
ADD ruby.spec /var/tmp/rpmbuild/SPECS/ruby.spec
ADD ruby-version /var/tmp/rpmbuild/SOURCES/ruby-version
