FROM centos:6.6
MAINTAINER hirokazu SUGIUCHI

# setup
RUN yum update -y
RUN yum install -y rpm-build tar

# ruby depends
RUN yum -y install readline-devel ncurses-devel gdbm-devel glibc-devel gcc openssl-devel libyaml-devel libffi-devel zlib-devel

# build
RUN mkdir -p /root/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
WORKDIR /root/rpmbuild
ADD rubybuild.sh /root/rpmbuild/rubybuild.sh
ADD ruby.spec /root/rpmbuild/SPECS/ruby.spec
ADD ruby-version /root/rpmbuild/SOURCES/ruby-version
